Register
NDBman/GroupNews pull request #2
Opened 2017-04-24 13:09 UTC by NDBman

Could test email's validity in service layer because Pattern and Matcher classes aren't mockable.

2017-04-24 17:38 UTC, uzonyib commented
Recommended: http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

2017-04-24 17:38 UTC, uzonyib requested changes

2017-04-24 17:38 UTC, uzonyib commented on groupnews-dao/src/main/java/com/epam/internship/entity/UserEntity.java
> +	@Column(nullable=false)
nullable = false

2017-04-24 17:38 UTC, uzonyib commented on groupnews-dao/src/main/java/com/epam/internship/entity/UserEntity.java
> +	@Column(unique= true)
unique = true

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
>  	public User createUser(String name, String email);
It is recommended to omit implicit public modifiers inside interfaces.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	public boolean emailAlreadyExists(String email);
As discussed, do not make validation methods public.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +	private final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
Please make it static.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
>  		User newUser = User.builder().name(name).email(email).build();
Validate email here please.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +			if(userEntity.getEmail().equals(email))
It is recommended to use curly braces ({}) even if there is only a single statement in the body of the if / for. This improves readability a lot.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +		if(matcher.find()){
if (matcher.find()) {
Formatting & readability!

2017-04-24 17:38 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +	private Pattern pattern = Pattern.compile(EMAIL_PATTERN);
Pattern can also be static.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +	@PostMapping(value="new")
I recommend mapping this functionality to POST /users. It is more REST-like.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-web/src/test/java/com/epam/internship/UserControllerTest.java
> +	private UserService systemUnderTest;
UserService is not the subject of your test, so please do not call it 'systemUnderTest'. It is misleading.

2017-04-24 17:38 UTC, uzonyib commented on groupnews-web/src/test/java/com/epam/internship/UserControllerTest.java
> +		.andDo(MockMvcResultHandlers.print())
Is this needed?

2017-04-24 17:38 UTC, uzonyib commented on groupnews-web/src/test/java/com/epam/internship/UserControllerTest.java
> +		.andDo(MockMvcResultHandlers.print())
Formatting! (Compare indentation to lines 69-73.)

2017-04-24 17:55 UTC, NDBman commented on groupnews-web/src/test/java/com/epam/internship/UserControllerTest.java
> +	private UserService systemUnderTest;
Yes, you are right, on the get_user branch I already fixed it.

2017-04-24 18:05 UTC, NDBman commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	public boolean emailAlreadyExists(String email);
I get this error : Cannot reduce the visibility of the inherited method from UserService.
Also, should I make it private then or other modifier would be needed?

2017-04-25 06:29 UTC, uzonyib requested changes

2017-04-25 06:29 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +		if(matcher.find()){
How about simply:
return matcher.find();

2017-04-25 06:29 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	public boolean emailAlreadyExists(String email);
Remove it from the interface and make it private in the implementation class.

2017-04-25 06:29 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	boolean emailAlreadyExists(String email);
This should also be removed from the interface.

2017-04-25 06:29 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	boolean emailAlreadyExists(String email);
Please remove this from the interface.

2017-04-25 11:06 UTC, Attila-Neuwirth commented on groupnews-web/src/test/java/com/epam/internship/UserControllerTest.java
> +				// Then
Please fix indentation.

2017-04-25 11:41 UTC, Attila-Neuwirth requested changes
My only concern is about indentation in general.
Please set it to 4 spaces.

2017-04-26 06:28 UTC, uzonyib approved these changes

2017-04-26 06:50 UTC, Attila-Neuwirth approved these changes

2017-04-26 06:50 UTC, merged