Get user
NDBman/GroupNews pull request #3
Opened 2017-04-24 13:42 UTC by NDBman

2017-04-24 17:48 UTC, uzonyib requested changes

2017-04-24 17:48 UTC, uzonyib commented on groupnews-service/src/test/java/com/epam/internship/UserServiceTest.java
> +		Mockito.when(systemUnderTest.getUserById(USER_ID_1)).thenReturn(user1);
You should not mock anything in systemUnderTest. Basically you are testing Mockito here.

2017-04-24 22:24 UTC, NDBman commented on groupnews-service/src/test/java/com/epam/internship/UserServiceTest.java
> +		Mockito.when(systemUnderTest.getUserById(USER_ID_1)).thenReturn(user1);
Yes, this was a mistake I was wanted to mock userRepository's findOne method..

2017-04-27 08:33 UTC, Attila-Neuwirth commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +		if (userService.isEmailValid(email)) {
This can be included in line 32, so you won't search the database for an invalid email.

2017-04-27 08:37 UTC, Attila-Neuwirth requested changes

2017-04-27 08:37 UTC, Attila-Neuwirth commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +		return new ResponseEntity<User>(userService.getUserById(id), HttpStatus.OK);
Don't query the database for the user again! You already have it in `user`.

2017-04-27 19:02 UTC, uzonyib requested changes

2017-04-27 19:02 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/UserService.java
> +	User getUserById(Long id) throws NotFoundException;
1. Please do not use javassist exceptions. For such purpuse, create a custom runtime exception.
2. It is better to use an unchecked exception in this case.

2017-04-27 19:02 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/UserServiceImpl.java
> +		if (user == null) {
You should check directly the repository's return value, not the converter's.

2017-04-27 19:02 UTC, uzonyib commented on groupnews-service/src/test/java/com/epam/internship/UserServiceTest.java
> +		System.out.println(user);
Please remove.

2017-04-27 19:02 UTC, uzonyib commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +		return new ResponseEntity<User>(userService.getUserById(id), HttpStatus.OK);
Why do you need ResponseEntity here? You can simple return the user without wrapping.

2017-04-28 19:04 UTC, uzonyib commented on groupnews-service/src/test/java/com/epam/internship/UserServiceTest.java
> -		System.out.println(user);
I meant to remove only the sysout, the test case is valid and should remain.

2017-04-30 16:32 UTC, uzonyib approved these changes

2017-05-02 11:08 UTC, Attila-Neuwirth approved these changes

2017-05-02 11:09 UTC, merged