Create group
NDBman/GroupNews pull request #5
Opened 2017-05-06 18:18 UTC by NDBman

2017-05-08 10:49 UTC, uzonyib requested changes

2017-05-08 10:49 UTC, uzonyib commented on groupnews-dao/src/main/java/com/epam/internship/entity/GroupEntity.java
> +	@OneToOne(cascade = CascadeType.ALL)
This relationship should be many to one.

2017-05-08 10:49 UTC, uzonyib commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +	public Group createGroup(@PathVariable("userId") Long userId, @RequestParam String title,
Please create a new controller for group related operations.

2017-05-08 10:49 UTC, uzonyib commented on groupnews-web/src/test/java/com/epam/internship/ExcpetionControllerTest.java
> -public class ExcpetionControllerTest {
Why did you delete this test class?

2017-05-08 10:53 UTC, NDBman commented on groupnews-web/src/test/java/com/epam/internship/ExcpetionControllerTest.java
> -public class ExcpetionControllerTest {
Because those cases were testing the UserController anyway so migrated them to UserControllerTest class.

2017-05-08 14:38 UTC, uzonyib approved these changes

2017-05-11 13:58 UTC, Attila-Neuwirth approved these changes

2017-05-11 13:59 UTC, merged