Logging
NDBman/GroupNews pull request #7
Opened 2017-05-09 20:35 UTC by NDBman

2017-05-10 08:47 UTC, uzonyib requested changes

2017-05-10 08:47 UTC, uzonyib commented on groupnews-web/src/main/resources/logback-test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this config for test context? It should be simply logback.xml to also ensure logging when you start the Boot app.

2017-05-10 11:01 UTC, NDBman commented on groupnews-web/src/main/resources/logback-test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
At logback's webpage in charter configuration it was written that firstly it tries to search for logback-test.xml so I guess I just created that file without think about the logic of it. Will correct it.

2017-05-10 11:01 UTC, NDBman commented on groupnews-web/src/main/resources/logback-test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Chapter*

2017-05-22 14:20 UTC, uzonyib approved these changes

2017-05-22 14:20 UTC, uzonyib commented on groupnews-web/src/main/java/com/epam/internship/controller/UserController.java
> +	final static Logger logger = LoggerFactory.getLogger(UserController.class);
private static final Logger LOG(GER)

2017-05-22 14:24 UTC, Attila-Neuwirth approved these changes

2017-05-22 14:54 UTC, merged