Membership
NDBman/GroupNews pull request #8
Opened 2017-05-14 22:26 UTC by NDBman

2017-05-22 14:25 UTC, uzonyib requested changes

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/GroupServiceImpl.java
> +	private MembershipRepository membershipRepostiroy;
Typo.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/MembershipServiceImpl.java
> +		System.out.println(membershipEntities);
:)

2017-05-22 14:25 UTC, uzonyib commented on groupnews-dao/src/main/java/com/epam/internship/entity/MembershipEntity.java
> +	private GroupEntity groupEntity;
I would remove "entity" from the attribute name. It is not consistent with the user attribute.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-dao/src/main/java/com/epam/internship/entity/MembershipEntity.java
> +	private UserEntity member;
Please do not allow nulls for any of the fields. Also add a unique constraint for user & group.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-dao/src/main/resources/data.sql
> +VALUES (1);
This insert statement does not seem to be complete and should not work (because of the unique constraint which I miss).

2017-05-22 14:25 UTC, uzonyib commented on groupnews-dao/src/test/java/com/epam/internship/MembershipRepositoryIT.java
> +		GroupEntity groupEntity = groupRepository.findOne(ID_1);
I would use different IDs for users and groups for readability and avoiding funny failures.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/converter/MembershipConverter.java
> +	private UserConverter userConverter = new UserConverter();
Why don't you autowire these dependent converters?

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/converter/MembershipEntityConverter.java
> +	private UserEntityConverter userEntityConverter = new UserEntityConverter();
Same as for MembershipConverter.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/dto/Membership.java
> +	private Role role;
Role is defined in the entity package, thus it shouldn't be used in DTOs.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/GroupServiceImpl.java
> +		membershipRepostiroy.save(membershipEntity);
Group should be created BEFORE creating a membership.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/MembershipServiceImpl.java
> +	public List<Membership> addUsersToGroup(Long groupId, List<Member> newMembers) {
The complexity of this method is pretty high. Please split it. Also take care of formatting.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/main/java/com/epam/internship/impl/MembershipServiceImpl.java
> +		for (MembershipEntity me : membershipRepository.findByGroupEntity(groupEntity)) {
Please replace this with some nice Java 8 stream based implementation.

2017-05-22 14:25 UTC, uzonyib commented on groupnews-service/src/test/java/com/epam/internship/MembershipConverterTest.java
> +	private UserConverter userConverter = new UserConverter();
User and group converters should be mocks.

2017-05-26 15:18 UTC, uzonyib approved these changes

2017-05-26 15:18 UTC, uzonyib commented on groupnews-dao/src/test/java/com/epam/internship/MembershipRepositoryIT.java
> +@SpringBootApplication
Is it needed?

2017-05-29 12:02 UTC, Attila-Neuwirth approved these changes

2017-06-20 22:06 UTC, merged